name: Cypress Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          node-version: 18
      
      - run: API_KEY=${{ secrets.CYPRESS_MAILSLURP_API_KEY }}  
      - run: npm ci
      - run: npx cypress run --browser chrome  